"""add document_type and structured_data

Revision ID: 94b1f62c74ed
Revises: a53741a518e2
Create Date: 2026-07-31 14:43:38.192339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b1f62c74ed'
down_revision: Union[str, Sequence[str], None] = 'a53741a518e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('structured_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'structured_data')
    op.drop_column('documents', 'document_type')
    # ### end Alembic commands ###
